name: sklearn-porter
channels:
- defaults
dependencies:
- ca-certificates=2018.03.07=0
- certifi=2018.10.15=py27_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1.20170329=hb402a30_2
- libffi=3.2.1=h475c297_4
- ncurses=6.1=h0a44026_0
- openssl=1.1.1=h1de35cc_0
- pip=10.0.1=py27_0
- python=2.7.15=h8f8e585_2
- readline=7.0=h1de35cc_5
- setuptools=40.4.3=py27_0
- sqlite=3.25.2=ha441bb4_0
- tk=8.6.8=ha441bb4_0
- wheel=0.32.2=py27_0
- zlib=1.2.11=hf3cbc9b_2
- pip:
  - protobuf==3.6.1
  - pycairo==1.17.1
  - six==1.11.0
  - tbb==0.1
prefix: /opt/miniconda/envs/sklearn-porter
